### PR TITLE
1086 total number of products fix

### LINKED ISSUE #1086: Total number of products should not include terminated subscriptions

### PR DESCRIPTION
**Pull request by ricardovdheijden**
#1086 

Adds extra filter to the query used in the summary card showing the total number of products

### CODE REVIEW

File: packages/orchestrator-ui-components/src/pages/startPage/queryVariables.ts [hunk 1]
```diff
@@ -100,12 +101,19 @@ export const taskListSummaryQueryVariables: GraphqlQueryVariables<Process> = {
...
+    first: 1000,
+    after: 0,
+    sortBy: {
+        field: 'name',
+        order: SortOrder.ASC,
+    },
+    filterBy: [
+        {
+            field: 'status',
+            value: `!${SubscriptionStatus.TERMINATED}`,
```
Comment (mrijk) [inline packages/orchestrator-ui-components/src/pages/startPage/queryVariables.ts:116]: I can imagine this filter happens quite a lot. Maybe have a couple of predefined field/value pairs?

File: packages/orchestrator-ui-components/src/pages/startPage/queryVariables.ts [hunk 2]
```diff
@@ -100,12 +101,19 @@ export const taskListSummaryQueryVariables: GraphqlQueryVariables<Process> = {
...
-    {
-        first: 1000,
-        after: 0,
-        sortBy: {
-            field: 'name',
-            order: SortOrder.ASC,
+export const productsSummaryQueryVariables: GraphqlQueryVariables<
+    ProductsSummary & Subscription
+> = {
+    first: 1000,
```
Comment (mrijk) [inline packages/orchestrator-ui-components/src/pages/startPage/queryVariables.ts:107]: Magic number.

File: packages/orchestrator-ui-components/src/pages/startPage/queryVariables.ts [hunk 3]
```diff
@@ -100,12 +101,19 @@ export const taskListSummaryQueryVariables: GraphqlQueryVariables<Process> = {
...
 
-export const productsSummaryQueryVariables: GraphqlQueryVariables<ProductsSummary> =
-    {
-        first: 1000,
-        after: 0,
-        sortBy: {
-            field: 'name',
-            order: SortOrder.ASC,
+export const productsSummaryQueryVariables: GraphqlQueryVariables<
+    ProductsSummary & Subscription
```
Comment (mrijk) [inline packages/orchestrator-ui-components/src/pages/startPage/queryVariables.ts:105]: I'm not very familiar with the typescript type system, but having a union type of a ProductSummary and a Subscription feels a bit weird, since they are kind of unrelated. Unless this is just meant as a quick way to avoid introducing 'real' types. In that case you might be better of with something like (if that is even possible): 'type myCombinedWhateverType = ProductsSummary & Subscription' and use that

Comment (ricardovdheijden) [reply packages/orchestrator-ui-components/src/pages/startPage/queryVariables.ts:105]: In this query both are actually related: counting the number of subscriptions per product

File: packages/orchestrator-ui-components/src/pages/startPage/queryVariables.ts (hunk 1 above)
Comment (ricardovdheijden) [reply packages/orchestrator-ui-components/src/pages/startPage/queryVariables.ts:116]: Indeed, when also used somewhere else we need to start introducing predefined filters. This is currently not the case

File: packages/orchestrator-ui-components/src/pages/startPage/queryVariables.ts (hunk 2 above)
Comment (ricardovdheijden) [reply packages/orchestrator-ui-components/src/pages/startPage/queryVariables.ts]: Replaced with a constant

**Review by mrijk — APPROVED** [review]
LGTM

**Review by DutchBen — APPROVED** [review]
