### PR TITLE
Fix errors caused by uniforms connectField

### LINKED ISSUE #681: The modify_subscription_references form on 1G SP does not load correctly

### PR DESCRIPTION
**Pull request by DutchBen**
Closes #681

### CODE REVIEW

File: packages/orchestrator-ui-components/src/components/WfoForms/formFields/ContactPersonNameField.tsx [hunk 1]
```diff
@@ -50,9 +50,10 @@ declare module 'uniforms' {
     interface FilterDOMProps {
         customerId: never;
         customerKey: never;
+        organisationKey: never;
```
Comment (tjeerddie) [inline packages/orchestrator-ui-components/src/components/WfoForms/formFields/ContactPersonNameField.tsx:53]: also add `organisationId`

**Review by tjeerddie — APPROVED** [review]

File: packages/orchestrator-ui-components/src/components/WfoForms/formFields/SelectField.tsx
Comment (Georgi2704) [inline packages/orchestrator-ui-components/src/components/WfoForms/formFields/SelectField.tsx:1]: Line 43 - 68 duplicated with ListSelectField

**Review by Georgi2704 — APPROVED** [review]

File: packages/orchestrator-ui-components/src/components/WfoForms/formFields/ContactPersonNameField.tsx (hunk 1 above)
Comment (DutchBen) [reply packages/orchestrator-ui-components/src/components/WfoForms/formFields/ContactPersonNameField.tsx:53]: done
